org.gradle.jvmargs=-Xmx512M -XX:+UseSerialGC -XX:ActiveProcessorCount=2 -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Djava.util.concurrent.ForkJoinPool.common.parallelism=2
android.useAndroidX=true
android.enableJetifier=false
org.gradle.parallel=false
org.gradle.configureondemand=true
android.defaults.buildfeatures.aarMetadataCheck=false
org.gradle.workers.max=2
